[package]
name = "serve-dir"
version = "0.2.1"
edition = "2021"

[dependencies]
base64 = "0.22.1"
sha1 = { version ="0.11.0-pre.3", default-features = false }
tokio = { version = "1.38.0", default-features = false, features = ["sync", "rt", "net", "io-util", "fs", "macros", "rt-multi-thread"] }
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"], optional = true }
clap = { version = "4.5.7", features = ["derive"], optional = true }

[features]
default = ["filesystem-events"]
filesystem-events = ["dep:notify"]
binary = ["dep:clap", "filesystem-events"]
